{
 "title": "Node Eth",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_block_number" }
   ]
  },
  {
   "title": "Blocks per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(eth_block_number[1m])" }
   ]
  },
  {
   "title": "Latest Block Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_latest_block_transactions" }
   ]
  },
  {
   "title": "Pending Block Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_pending_block_transactions" }
   ]
  },
  {
   "title": "Net Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "net_peers" }
   ]
  }
 ]
}